CREATE TABLE IF NOT EXISTS T001_RECEIPTS (
	id TEXT PRIMARY KEY,
	date TEXT NOT NULL,
	store_name TEXT NOT NULL,
	total INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS T002_RECEIPT_ITEMS (
	receipt_id TEXT NOT NULL,
	name TEXT NOT NULL,
	price INTEGER NOT NULL,
	quantity INTEGER NOT NULL,
	FOREIGN KEY (receipt_id) REFERENCES T001_RECEIPTS(id) ON DELETE CASCADE
);